import { defineConfig } from 'orval';

export default defineConfig({
  // api: {
  //   output: {
  //     target: './apps/vite/src/lib/swr-client',
  //     schemas: './apps/vite/src/lib/swr-client/models',
  //     mode: 'tags-split',
  //     mock: true,
  //     client: 'swr',
  //     clean: true,
  //     indexFiles: true,
  //     prettier: true,
  //   },
  //   input: {
  //     target: './apps/document/api/open-api.yaml',
  //   },
  // },
  tanctack: {
    output: {
      workspace: './apps/vite/src/lib/tanctack-client/',
      target: '.',
      schemas: './models',
      mode: 'tags-split',
      mock: true,
      client: 'react-query',
      clean: true,
      indexFiles: true,
      override: {
        header: (info): string[] => [
          'Generated by orval 🍺',
          '手動で編集しないでください。',
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
          ...(info.version ? [`OpenAPIスペックバージョン: ${info.version}`] : []),
          '@ts-nocheck',
        ],
        query: {
          useQuery: false,
          useInfinite: false,
          useSuspenseQuery: true,
          useSuspenseInfiniteQuery: true,
          version: 5,
        },
      },
    },
    input: {
      target: './apps/document/api/open-api.yaml',
    },
    hooks: {
      afterAllFilesWrite: 'biome format --write',
    },
  },
  // zod: {
  //   output: {
  //     target: './apps/vite/src/lib/zod-schema',
  //     schemas: './apps/vite/src/lib/zod-schema/models',
  //     mode: 'tags-split',
  //     client: 'zod',
  //     clean: true,
  //     indexFiles: true,
  //   },
  //   input: {
  //     target: './apps/document/api/open-api.yaml',
  //   },
  //   hooks: {
  //     afterAllFilesWrite: 'biome check --apply',
  //   },
  // },
});
