/**
 * Generated by orval 🍺
 * 手動で編集しないでください。
 * ToDo API
 * ToDoアプリのAPI仕様書
 * OpenAPIスペックバージョン: 1.0.0
 * @ts-nocheck
 */
import { useMutation, useSuspenseInfiniteQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  InfiniteData,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';
import type { GetTodos200Item, PatchTodosIdBody, PostTodosBody } from '.././models';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary ToDo一覧を取得
 */
export const getTodos = (options?: AxiosRequestConfig): Promise<AxiosResponse<GetTodos200Item[]>> => {
  return axios.get(`/todos`, options);
};

export const getGetTodosQueryKey = () => {
  return [`/todos`] as const;
};

export const getGetTodosSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getTodos>>,
  TError = AxiosError<void>,
>(options?: {
  query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>>;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTodosQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodos>>> = ({ signal }) =>
    getTodos({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getTodos>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetTodosSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getTodos>>>;
export type GetTodosSuspenseQueryError = AxiosError<void>;

/**
 * @summary ToDo一覧を取得
 */
export const useGetTodosSuspense = <TData = Awaited<ReturnType<typeof getTodos>>, TError = AxiosError<void>>(options?: {
  query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>>;
  axios?: AxiosRequestConfig;
}): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetTodosSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getGetTodosSuspenseInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getTodos>>>,
  TError = AxiosError<void>,
>(options?: {
  query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>>;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTodosQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodos>>> = ({ signal }) =>
    getTodos({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getTodos>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetTodosSuspenseInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getTodos>>>;
export type GetTodosSuspenseInfiniteQueryError = AxiosError<void>;

/**
 * @summary ToDo一覧を取得
 */
export const useGetTodosSuspenseInfinite = <
  TData = InfiniteData<Awaited<ReturnType<typeof getTodos>>>,
  TError = AxiosError<void>,
>(options?: {
  query?: Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof getTodos>>, TError, TData>>;
  axios?: AxiosRequestConfig;
}): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getGetTodosSuspenseInfiniteQueryOptions(options);

  const query = useSuspenseInfiniteQuery(queryOptions) as UseSuspenseInfiniteQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary 新しいToDoを作成する
 */
export const postTodos = (postTodosBody: PostTodosBody, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> => {
  return axios.post(`/todos`, postTodosBody, options);
};

export const getPostTodosMutationOptions = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postTodos>>, TError, { data: PostTodosBody }, TContext>;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof postTodos>>, TError, { data: PostTodosBody }, TContext> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postTodos>>, { data: PostTodosBody }> = (props) => {
    const { data } = props ?? {};

    return postTodos(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostTodosMutationResult = NonNullable<Awaited<ReturnType<typeof postTodos>>>;
export type PostTodosMutationBody = PostTodosBody;
export type PostTodosMutationError = AxiosError<unknown>;

/**
 * @summary 新しいToDoを作成する
 */
export const usePostTodos = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postTodos>>, TError, { data: PostTodosBody }, TContext>;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getPostTodosMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary ToDoを更新する
 */
export const patchTodosId = (
  id: number,
  patchTodosIdBody: PatchTodosIdBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.patch(`/todos/${id}`, patchTodosIdBody, options);
};

export const getPatchTodosIdMutationOptions = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchTodosId>>,
    TError,
    { id: number; data: PatchTodosIdBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchTodosId>>,
  TError,
  { id: number; data: PatchTodosIdBody },
  TContext
> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchTodosId>>,
    { id: number; data: PatchTodosIdBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return patchTodosId(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchTodosIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchTodosId>>>;
export type PatchTodosIdMutationBody = PatchTodosIdBody;
export type PatchTodosIdMutationError = AxiosError<unknown>;

/**
 * @summary ToDoを更新する
 */
export const usePatchTodosId = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchTodosId>>,
    TError,
    { id: number; data: PatchTodosIdBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getPatchTodosIdMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary ToDoを削除する
 */
export const deleteTodosId = (id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> => {
  return axios.delete(`/todos/${id}`, options);
};

export const getDeleteTodosIdMutationOptions = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteTodosId>>, TError, { id: number }, TContext>;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteTodosId>>, TError, { id: number }, TContext> => {
  const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTodosId>>, { id: number }> = (props) => {
    const { id } = props ?? {};

    return deleteTodosId(id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteTodosIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTodosId>>>;

export type DeleteTodosIdMutationError = AxiosError<unknown>;

/**
 * @summary ToDoを削除する
 */
export const useDeleteTodosId = <TError = AxiosError<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteTodosId>>, TError, { id: number }, TContext>;
  axios?: AxiosRequestConfig;
}) => {
  const mutationOptions = getDeleteTodosIdMutationOptions(options);

  return useMutation(mutationOptions);
};
