/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * ToDo API
 * ToDoアプリのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */

export type GetTodos200Item = {
  /** ToDoの日付 */
  date: string;
  /** ToDoが完了したかどうか */
  done: boolean;
  /** ToDoのID */
  id: number;
  /** ToDoが"いいね"されたかどうか */
  nice: boolean;
  /** ToDoのタイトル */
  title: string;
};
