/**
 * Generated by orval 🍺
 * 手動で編集しないでください。
 * ToDo API
 * ToDoアプリのAPI仕様書
 * OpenAPIスペックバージョン: 1.0.0
 * @ts-nocheck
 */

export type GetTodos200Item = {
  /** ToDoの日付 */
  date: string;
  /** ToDoが完了したかどうか */
  done: boolean;
  /** ToDoのID */
  id: number;
  /** ToDoが"いいね"されたかどうか */
  nice: boolean;
  /** ToDoのタイトル */
  title: string;
};
