/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * ToDo API
 * ToDoアプリのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */

export type PatchTodosIdBody = {
  /** ToDoの日付 */
  date: string | null;
  /** ToDoが完了したかどうか */
  done: boolean | null;
  /** ToDoが"いいね"されたかどうか */
  nice: boolean | null;
  /** ToDoのタイトル */
  title: string;
};
